/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import java.awt.PopupMenu;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author 50765
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        TituloLogin = new javax.swing.JLabel();
        usuariotext = new javax.swing.JTextField();
        imgps = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        TituloPasword = new javax.swing.JLabel();
        titulousuario = new javax.swing.JLabel();
        PerfilImg = new javax.swing.JLabel();
        Circulo = new javax.swing.JLabel();
        imagnn = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        Botonsalir = new javax.swing.JButton();
        fondologin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 600));

        panelfondo.setMinimumSize(new java.awt.Dimension(640, 540));
        panelfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloLogin.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        TituloLogin.setForeground(new java.awt.Color(204, 255, 255));
        TituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLogin.setText("MIEMBRO LOGIN ");
        panelfondo.add(TituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 190, 40));

        usuariotext.setBackground(new java.awt.Color(153, 153, 255));
        usuariotext.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        usuariotext.setForeground(new java.awt.Color(51, 51, 51));
        usuariotext.setToolTipText("Usuario@gmail.com");
        usuariotext.setAlignmentX(0.3F);
        usuariotext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 102), new java.awt.Color(102, 0, 102)));
        panelfondo.add(usuariotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 280, 30));

        imgps.setForeground(new java.awt.Color(255, 245, 245));
        imgps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneslogin/candado3 (1).png"))); // NOI18N
        imgps.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        imgps.setOpaque(true);
        panelfondo.add(imgps, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 30, 30));

        contraseña.setBackground(new java.awt.Color(153, 153, 255));
        contraseña.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(51, 51, 51));
        contraseña.setToolTipText("Digite Contraseña");
        contraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), new java.awt.Color(51, 0, 51)));
        panelfondo.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 280, 30));

        TituloPasword.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        TituloPasword.setForeground(new java.awt.Color(255, 255, 255));
        TituloPasword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPasword.setText("Contraseña");
        panelfondo.add(TituloPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 90, -1));

        titulousuario.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        titulousuario.setForeground(new java.awt.Color(255, 255, 255));
        titulousuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulousuario.setText("Usuario");
        panelfondo.add(titulousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 80, 20));

        PerfilImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneslogin/UsuarioRed.png"))); // NOI18N
        PerfilImg.setFocusable(false);
        PerfilImg.setPreferredSize(new java.awt.Dimension(230, 230));
        panelfondo.add(PerfilImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 210));

        Circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneslogin/Circulo Celeste2.png"))); // NOI18N
        panelfondo.add(Circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, 230));

        imagnn.setForeground(new java.awt.Color(250, 231, 255));
        imagnn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneslogin/etiquetausuariocaja.png"))); // NOI18N
        imagnn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 102)));
        imagnn.setOpaque(true);
        panelfondo.add(imagnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 30, 30));

        iniciar.setBackground(new java.awt.Color(102, 102, 255));
        iniciar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        iniciar.setForeground(new java.awt.Color(204, 255, 255));
        iniciar.setText("INICIAR SESION");
        iniciar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 0, 204)));
        iniciar.setOpaque(true);
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        iniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iniciarKeyReleased(evt);
            }
        });
        panelfondo.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 140, 30));

        Botonsalir.setBackground(new java.awt.Color(0, 153, 255));
        Botonsalir.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Botonsalir.setForeground(new java.awt.Color(204, 204, 255));
        Botonsalir.setText("SALIR");
        Botonsalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 153), new java.awt.Color(51, 0, 51)));
        Botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsalirActionPerformed(evt);
            }
        });
        panelfondo.add(Botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 50, 30));

        fondologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneslogin/FondoLoginP.jpg"))); // NOI18N
        panelfondo.add(fondologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        
        String usuario = "Brayanalt@gmail.com";
        String pass = "";
        String contrase = "brayanal123"; 
        char password[] = contraseña.getPassword();

        for (int i = 0; i < password.length; i++) {
            pass += password[i];// Guardo lo que escribo en string 
        }

        if (usuariotext.getText().equals(usuario)&& (pass.equals(contrase))) {     
            JOptionPane.showMessageDialog(null, "\t[Bienvenido a Mi Programa]"+"\nAcceso Permitido ,Contraseña y Usuario Correcta");
         
        }
        else if ((usuariotext.getText().equals("")) || (pass.equals(""))) {
            JOptionPane.showMessageDialog(null, " Error Espacios en Blanco " ,"Revisar",JOptionPane.WARNING_MESSAGE);
        } 
        
        else {
            JOptionPane.showMessageDialog(null, "Acceso Denegado , Usuario o Contraseña Incorrecto ", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
        } 
        
        
        


    }//GEN-LAST:event_iniciarActionPerformed
    
    private void BotonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BotonsalirActionPerformed

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        
    }//GEN-LAST:event_iniciarMouseClicked

    private void iniciarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iniciarKeyReleased
        
    }//GEN-LAST:event_iniciarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonsalir;
    private javax.swing.JLabel Circulo;
    private javax.swing.JLabel PerfilImg;
    private javax.swing.JLabel TituloLogin;
    private javax.swing.JLabel TituloPasword;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondologin;
    private javax.swing.JLabel imagnn;
    private javax.swing.JLabel imgps;
    private javax.swing.JButton iniciar;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JLabel titulousuario;
    private javax.swing.JTextField usuariotext;
    // End of variables declaration//GEN-END:variables
}
